Develop
EgorZhuganov/java-filmorate pull request #1
Opened 2022-04-25 11:05 UTC by EgorZhuganov

Add controllers: FilmController, UserController
Add dtos
Add mappers
Add models
Add repositories
Add services
Add annotation for validation

2022-04-26 20:12 UTC, kukolev requested changes

2022-04-26 20:12 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    FilmControllerTest() throws JsonProcessingException {}
По моему этот конструктор не нужен. Он не делает ничего полезного. Бесполезный код нужно удалять, чтобы не отвлекал.

2022-04-26 20:12 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +    UserControllerTest() throws JsonProcessingException {
По моему этот конструктор не нужен. Он не делает ничего полезного. Бесполезный код нужно удалять, чтобы не отвлекал.

2022-04-26 20:12 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/dto/filmDto/FilmCreateDtoTest.java
> +    FilmService service;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-04-26 20:12 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/dto/filmDto/FilmUpdateDtoTest.java
> +    @Autowired FilmService service;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-04-26 20:12 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/dto/userDto/UserCreateDtoTest.java
> +    @Autowired UserService service;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-04-26 20:12 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/dto/userDto/UserUpdateDtoTest.java
> +    @Autowired UserService service;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-04-26 20:12 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/service/FilmServiceTest.java
> +    FilmService service;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-04-26 20:12 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/service/UserServiceTest.java
> +    UserService service;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-04-26 20:12 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/dto/userDto/UserCreateDtoTest.java
> +                "MyDisplayName", LocalDate.of(1998,12,12));
Нарушение кодстайла: Не хватает пробелов после запятых перед числами. Советую в IDEA просто нажать комбинацию клавиш  Ctrl + Alt + L и код автоматически отформатируется.

2022-04-26 20:12 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/dto/userDto/UserUpdateDtoTest.java
> +            "MyDisplayName", LocalDate.of(1998,12,12));
Нарушение кодстайла: Не хватает пробелов после запятых перед числами. Советую в IDEA просто нажать комбинацию клавиш  Ctrl + Alt + L и код автоматически отформатируется.

2022-04-26 20:12 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/mapper/filmMapper/FilmCreateMapperTest.java
> +            LocalDate.of(1971,6,21), Duration.ofMinutes(161));
Нарушение кодстайла: Не хватает пробелов после запятых перед числами. Советую в IDEA просто нажать комбинацию клавиш  Ctrl + Alt + L и код автоматически отформатируется.

2022-04-26 20:12 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/mapper/filmMapper/FilmUpdateMapperTest.java
> +            LocalDate.of(1971,6,21), Duration.ofMinutes(161));
Нарушение кодстайла: Не хватает пробелов после запятых перед числами. Советую в IDEA просто нажать комбинацию клавиш  Ctrl + Alt + L и код автоматически отформатируется.

2022-04-26 20:12 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/mapper/userMapper/UserCreateMapperTest.java
> +            "myDisplayName", LocalDate.of(2000,1,1));
Нарушение кодстайла: Не хватает пробелов после запятых перед числами. Советую в IDEA просто нажать комбинацию клавиш  Ctrl + Alt + L и код автоматически отформатируется.

2022-04-26 20:12 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/mapper/userMapper/UserUpdateMapperTest.java
> +            "myDisplayName", LocalDate.of(1984,12,12));
Нарушение кодстайла: Не хватает пробелов после запятых перед числами. Советую в IDEA просто нажать комбинацию клавиш  Ctrl + Alt + L и код автоматически отформатируется.

2022-04-26 20:12 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/mapper/Mapper.java
> +    default T mapFrom(F fromObject, T toObject){
По моему этот метод и те методы, что его оверрайдят не нужны. Метод никак не использует fromObject. Если его убрать, то получится, что метод возвращает входной параметр. Такой метод не имеет смысла. Лучше код не усложнять, а делать проще. Лучший код это код, которые не написан.

2022-04-26 23:04 UTC, EgorZhuganov commented on pom.xml
> +		<!--		<dependency>-->
Удалил.

2022-04-26 23:04 UTC, EgorZhuganov commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +	public static void main(String[] args) {
В моем проекте все ок, лишних отступов нет.

2022-04-26 23:05 UTC, EgorZhuganov commented on src/main/java/ru/yandex/practicum/filmorate/dto/filmDto/FilmCreateDto.java
> +    String name;
Принцип инкапсуляции не нарушен т.к. над классом стоит аннотаци @Value (что означает private final), либо @FieldDefaults(level = AccessLevel.PRIVATE)

2022-04-26 23:06 UTC, EgorZhuganov commented on src/main/java/ru/yandex/practicum/filmorate/dto/filmDto/FilmReadDto.java
> +    Long id;
Принцип инкапсуляции не нарушен т.к. над классом стоит аннотаци @Value (что означает private final), либо @FieldDefaults(level = AccessLevel.PRIVATE)

2022-04-26 23:06 UTC, EgorZhuganov commented on src/main/java/ru/yandex/practicum/filmorate/dto/filmDto/FilmUpdateDto.java
> +    Long id;
Принцип инкапсуляции не нарушен т.к. над классом стоит аннотаци @Value (что означает private final), либо @FieldDefaults(level = AccessLevel.PRIVATE)

2022-04-26 23:06 UTC, EgorZhuganov commented on src/main/java/ru/yandex/practicum/filmorate/dto/userDto/UserCreateDto.java
> +    String email;
Принцип инкапсуляции не нарушен т.к. над классом стоит аннотаци @Value (что означает private final), либо @FieldDefaults(level = AccessLevel.PRIVATE)

2022-04-26 23:06 UTC, EgorZhuganov commented on src/main/java/ru/yandex/practicum/filmorate/dto/userDto/UserReadDto.java
> +    Long id;
Принцип инкапсуляции не нарушен т.к. над классом стоит аннотаци @Value (что означает private final), либо @FieldDefaults(level = AccessLevel.PRIVATE)

2022-04-26 23:06 UTC, EgorZhuganov commented on src/main/java/ru/yandex/practicum/filmorate/dto/userDto/UserUpdateDto.java
> +    Long id;
Принцип инкапсуляции не нарушен т.к. над классом стоит аннотаци @Value (что означает private final), либо @FieldDefaults(level = AccessLevel.PRIVATE)

2022-04-26 23:07 UTC, EgorZhuganov commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	@Test
В моем проекте все ок, лишних отступов нет.

2022-04-26 23:07 UTC, EgorZhuganov commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    FilmControllerTest() throws JsonProcessingException {}
Конструктор нужен для того, чтобы можно было написать эту строку перед всеми тестами:
private String filmAsJson = new ObjectMapper()
            .registerModule(new JavaTimeModule())
            .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)
            .disable(SerializationFeature.WRITE_DURATIONS_AS_TIMESTAMPS)
            .writeValueAsString(filmCreateDto1);

2022-04-26 23:08 UTC, EgorZhuganov commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +    UserControllerTest() throws JsonProcessingException {
Конструктор нужен, чтобы написать эту строку перед всеми тестами:
private String userAsJson = new ObjectMapper()
            .registerModule(new JavaTimeModule())
            .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)
            .writeValueAsString(userCreateDto1);

2022-04-26 23:08 UTC, EgorZhuganov commented on src/test/java/ru/yandex/practicum/filmorate/dto/filmDto/FilmCreateDtoTest.java
> +    FilmService service;
Исправил.

2022-04-26 23:09 UTC, EgorZhuganov commented on src/test/java/ru/yandex/practicum/filmorate/dto/filmDto/FilmUpdateDtoTest.java
> +    @Autowired FilmService service;
Исправил.

2022-04-26 23:10 UTC, EgorZhuganov commented on src/test/java/ru/yandex/practicum/filmorate/dto/userDto/UserCreateDtoTest.java
> +    @Autowired UserService service;
Исправил.

2022-04-26 23:10 UTC, EgorZhuganov commented on src/test/java/ru/yandex/practicum/filmorate/dto/userDto/UserUpdateDtoTest.java
> +    @Autowired UserService service;
Исправил.

2022-04-26 23:11 UTC, EgorZhuganov commented on src/test/java/ru/yandex/practicum/filmorate/service/FilmServiceTest.java
> +    FilmService service;
Исправил

2022-04-26 23:11 UTC, EgorZhuganov commented on src/test/java/ru/yandex/practicum/filmorate/service/UserServiceTest.java
> +    UserService service;
Исправил

2022-04-26 23:14 UTC, EgorZhuganov commented on src/test/java/ru/yandex/practicum/filmorate/dto/userDto/UserCreateDtoTest.java
> +                "MyDisplayName", LocalDate.of(1998,12,12));
Исправил

2022-04-26 23:14 UTC, EgorZhuganov commented on src/test/java/ru/yandex/practicum/filmorate/dto/userDto/UserUpdateDtoTest.java
> +            "MyDisplayName", LocalDate.of(1998,12,12));
Исправил

2022-04-26 23:14 UTC, EgorZhuganov commented on src/test/java/ru/yandex/practicum/filmorate/mapper/filmMapper/FilmCreateMapperTest.java
> +            LocalDate.of(1971,6,21), Duration.ofMinutes(161));
Исправил

2022-04-26 23:14 UTC, EgorZhuganov commented on src/test/java/ru/yandex/practicum/filmorate/mapper/filmMapper/FilmUpdateMapperTest.java
> +            LocalDate.of(1971,6,21), Duration.ofMinutes(161));
Исправил

2022-04-26 23:14 UTC, EgorZhuganov commented on src/test/java/ru/yandex/practicum/filmorate/mapper/userMapper/UserCreateMapperTest.java
> +            "myDisplayName", LocalDate.of(2000,1,1));
Исправил

2022-04-26 23:15 UTC, EgorZhuganov commented on src/test/java/ru/yandex/practicum/filmorate/mapper/userMapper/UserUpdateMapperTest.java
> +            "myDisplayName", LocalDate.of(1984,12,12));
Исправил

2022-04-27 04:11 UTC, EgorZhuganov commented on src/main/java/ru/yandex/practicum/filmorate/mapper/Mapper.java
> +    default T mapFrom(F fromObject, T toObject){
Удалил интерфейс, т.к. возникли проблемы: не все наследники должны соблюдать контракт T mapFrom(F objcet), т.к. UpdateMapper должен обновлять уже созданный объект, а не создавать новый.
Исправил, спасибо.

2022-04-27 06:18 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/mapper/Mapper.java
> +    default T mapFrom(F fromObject, T toObject){
Отлично, по моему стало проще.

2022-04-27 06:19 UTC, kukolev approved these changes

2022-04-27 07:18 UTC, merged